# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import components_pb2 as components__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in components_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComponentSeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllComponents = channel.unary_unary(
                '/ComponentSevice/GetAllComponents',
                request_serializer=components__pb2.Empty.SerializeToString,
                response_deserializer=components__pb2.ComponentList.FromString,
                _registered_method=True)
        self.AddComponent = channel.unary_unary(
                '/ComponentSevice/AddComponent',
                request_serializer=components__pb2.ComponentRequest.SerializeToString,
                response_deserializer=components__pb2.ComponentResponse.FromString,
                _registered_method=True)
        self.LoadComponentsFromJson = channel.unary_unary(
                '/ComponentSevice/LoadComponentsFromJson',
                request_serializer=components__pb2.Empty.SerializeToString,
                response_deserializer=components__pb2.ComponentResponse.FromString,
                _registered_method=True)


class ComponentSeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAllComponents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadComponentsFromJson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComponentSeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllComponents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllComponents,
                    request_deserializer=components__pb2.Empty.FromString,
                    response_serializer=components__pb2.ComponentList.SerializeToString,
            ),
            'AddComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.AddComponent,
                    request_deserializer=components__pb2.ComponentRequest.FromString,
                    response_serializer=components__pb2.ComponentResponse.SerializeToString,
            ),
            'LoadComponentsFromJson': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadComponentsFromJson,
                    request_deserializer=components__pb2.Empty.FromString,
                    response_serializer=components__pb2.ComponentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ComponentSevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ComponentSevice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComponentSevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAllComponents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ComponentSevice/GetAllComponents',
            components__pb2.Empty.SerializeToString,
            components__pb2.ComponentList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ComponentSevice/AddComponent',
            components__pb2.ComponentRequest.SerializeToString,
            components__pb2.ComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadComponentsFromJson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ComponentSevice/LoadComponentsFromJson',
            components__pb2.Empty.SerializeToString,
            components__pb2.ComponentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
