# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: components.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'components.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63omponents.proto\"\x07\n\x05\x45mpty\"f\n\x10\x43omponentRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x03 \x01(\t\x12\r\n\x05issue\x18\x04 \x01(\t\x12\x11\n\tspec_json\x18\x05 \x01(\t\"$\n\x11\x43omponentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"k\n\tComponent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x14\n\x0cmanufacturer\x18\x04 \x01(\t\x12\r\n\x05issue\x18\x05 \x01(\t\x12\x11\n\tspec_json\x18\x06 \x01(\t\"/\n\rComponentList\x12\x1e\n\ncomponents\x18\x01 \x03(\x0b\x32\n.Component2\xaa\x01\n\x0f\x43omponentSevice\x12*\n\x10GetAllComponents\x12\x06.Empty\x1a\x0e.ComponentList\x12\x35\n\x0c\x41\x64\x64\x43omponent\x12\x11.ComponentRequest\x1a\x12.ComponentResponse\x12\x34\n\x16LoadComponentsFromJson\x12\x06.Empty\x1a\x12.ComponentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'components_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_COMPONENTREQUEST']._serialized_start=29
  _globals['_COMPONENTREQUEST']._serialized_end=131
  _globals['_COMPONENTRESPONSE']._serialized_start=133
  _globals['_COMPONENTRESPONSE']._serialized_end=169
  _globals['_COMPONENT']._serialized_start=171
  _globals['_COMPONENT']._serialized_end=278
  _globals['_COMPONENTLIST']._serialized_start=280
  _globals['_COMPONENTLIST']._serialized_end=327
  _globals['_COMPONENTSEVICE']._serialized_start=330
  _globals['_COMPONENTSEVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
