# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth_service.proto\"S\n\x13RegistrationRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x18\n\x10\x63onfrim_password\x18\x03 \x01(\t\"8\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2n\n\x0b\x41uthService\x12\x37\n\x08Register\x12\x14.RegistrationRequest\x1a\x15.RegistrationResponse\x12&\n\x05Login\x12\r.LoginRequest\x1a\x0e.LoginResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTRATIONREQUEST']._serialized_start=22
  _globals['_REGISTRATIONREQUEST']._serialized_end=105
  _globals['_REGISTRATIONRESPONSE']._serialized_start=107
  _globals['_REGISTRATIONRESPONSE']._serialized_end=163
  _globals['_LOGINREQUEST']._serialized_start=165
  _globals['_LOGINREQUEST']._serialized_end=215
  _globals['_LOGINRESPONSE']._serialized_start=217
  _globals['_LOGINRESPONSE']._serialized_end=266
  _globals['_AUTHSERVICE']._serialized_start=268
  _globals['_AUTHSERVICE']._serialized_end=378
# @@protoc_insertion_point(module_scope)
