CREATE TABLE IF NOT EXISTS users(
    users_id SERIAL PRIMARY KEY,
    user_login CHARACTER VARYING(50) NOT NULL UNIQUE,
    password_hash BYTEA NOT NULL UNIQUE,
    user_role CHARACTER VARYING(50) NOT NULL
)